name: Generate Snake Animation 🐍

on:
  schedule:
    - cron: "0 0 * * *"  # roda todo dia à meia-noite
  workflow_dispatch:     # permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: LerronF
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit e push do SVG
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: atualiza snake 🐍"
          add: "dist/*.svg"

      - name: Move arquivo para pasta correta
        run: |
          mkdir -p output
          mv dist/github-contribution-grid-snake.svg output/
